-- Сокращения для КЛАДР.

DROP TABLE IF EXISTS socrbase;

CREATE TABLE socrbase (
    level character varying(5),
    scname character varying(10),
    socrname character varying(29),
    kod_t_st character varying(3)
);

INSERT INTO socrbase VALUES ('1', 'АО', 'Автономный округ', '101');
INSERT INTO socrbase VALUES ('1', 'Аобл', 'Автономная область', '102');
INSERT INTO socrbase VALUES ('1', 'Респ', 'Республика', '106');
INSERT INTO socrbase VALUES ('1', 'г', 'Город', '103');
INSERT INTO socrbase VALUES ('1', 'край', 'Край', '104');
INSERT INTO socrbase VALUES ('1', 'обл', 'Область', '105');
INSERT INTO socrbase VALUES ('1', 'округ', 'Округ', '107');
INSERT INTO socrbase VALUES ('2', 'АО', 'Автономный округ', '205');
INSERT INTO socrbase VALUES ('2', 'р-н', 'Район', '201');
INSERT INTO socrbase VALUES ('2', 'тер', 'Территория', '203');
INSERT INTO socrbase VALUES ('2', 'у', 'Улус', '202');
INSERT INTO socrbase VALUES ('3', 'волость', 'Волость', '310');
INSERT INTO socrbase VALUES ('3', 'г', 'Город', '301');
INSERT INTO socrbase VALUES ('3', 'дп', 'Дачный поселок', '305');
INSERT INTO socrbase VALUES ('3', 'кп', 'Курортный поселок', '304');
INSERT INTO socrbase VALUES ('3', 'п/о', 'Почтовое отделение', '311');
INSERT INTO socrbase VALUES ('3', 'пгт', 'Поселок городского типа', '302');
INSERT INTO socrbase VALUES ('3', 'рп', 'Рабочий поселок', '303');
INSERT INTO socrbase VALUES ('3', 'с/а', 'Сельская администрация', '307');
INSERT INTO socrbase VALUES ('3', 'с/мо', 'Сельское муниципальное образо', '315');
INSERT INTO socrbase VALUES ('3', 'с/о', 'Сельский округ', '309');
INSERT INTO socrbase VALUES ('3', 'с/п', 'Сельское поселение', '314');
INSERT INTO socrbase VALUES ('3', 'с/с', 'Сельсовет', '306');
INSERT INTO socrbase VALUES ('3', 'тер', 'Территория', '312');
INSERT INTO socrbase VALUES ('4', 'аал', 'Аал', '401');
INSERT INTO socrbase VALUES ('4', 'арбан', 'Арбан', '440');
INSERT INTO socrbase VALUES ('4', 'аул', 'Аул', '402');
INSERT INTO socrbase VALUES ('4', 'волость', 'Волость', '403');
INSERT INTO socrbase VALUES ('4', 'высел', 'Выселки(ок)', '404');
INSERT INTO socrbase VALUES ('4', 'г', 'Город', '405');
INSERT INTO socrbase VALUES ('4', 'городок', 'Городок', '436');
INSERT INTO socrbase VALUES ('4', 'д', 'Деревня', '406');
INSERT INTO socrbase VALUES ('4', 'дп', 'Дачный поселок', '407');
INSERT INTO socrbase VALUES ('4', 'ж/д_будка', 'Железнодорожная будка', '408');
INSERT INTO socrbase VALUES ('4', 'ж/д_казарм', 'Железнодорожная казарма', '409');
INSERT INTO socrbase VALUES ('4', 'ж/д_оп', 'ж/д останов. (обгонный) пункт', '410');
INSERT INTO socrbase VALUES ('4', 'ж/д_платф', 'Железнодорожная платформа', '438');
INSERT INTO socrbase VALUES ('4', 'ж/д_пост', 'Железнодорожный пост', '411');
INSERT INTO socrbase VALUES ('4', 'ж/д_рзд', 'Железнодорожный разъезд', '412');
INSERT INTO socrbase VALUES ('4', 'ж/д_ст', 'Железнодорожная станция', '413');
INSERT INTO socrbase VALUES ('4', 'заимка', 'Заимка', '414');
INSERT INTO socrbase VALUES ('4', 'казарма', 'Казарма', '415');
INSERT INTO socrbase VALUES ('4', 'кв-л', 'Квартал', '439');
INSERT INTO socrbase VALUES ('4', 'кордон', 'Кордон', '444');
INSERT INTO socrbase VALUES ('4', 'кп', 'Курортный поселок', '416');
INSERT INTO socrbase VALUES ('4', 'лпх', 'Леспромхоз', '442');
INSERT INTO socrbase VALUES ('4', 'м', 'Местечко', '417');
INSERT INTO socrbase VALUES ('4', 'мкр', 'Микрорайон', '418');
INSERT INTO socrbase VALUES ('4', 'нп', 'Населенный пункт', '419');
INSERT INTO socrbase VALUES ('4', 'остров', 'Остров', '420');
INSERT INTO socrbase VALUES ('4', 'п', 'Поселок', '421');
INSERT INTO socrbase VALUES ('4', 'п/о', 'Почтовое отделение', '426');
INSERT INTO socrbase VALUES ('4', 'п/р', 'Планировочный район', '422');
INSERT INTO socrbase VALUES ('4', 'п/ст', 'Поселок и(при) станция(и)', '423');
INSERT INTO socrbase VALUES ('4', 'пгт', 'Поселок городского типа', '424');
INSERT INTO socrbase VALUES ('4', 'погост', 'Погост', '443');
INSERT INTO socrbase VALUES ('4', 'починок', 'Починок', '425');
INSERT INTO socrbase VALUES ('4', 'промзона', 'Промышленная зона', '427');
INSERT INTO socrbase VALUES ('4', 'рзд', 'Разъезд', '428');
INSERT INTO socrbase VALUES ('4', 'рп', 'Рабочий поселок', '429');
INSERT INTO socrbase VALUES ('4', 'с', 'Село', '430');
INSERT INTO socrbase VALUES ('4', 'сл', 'Слобода', '431');
INSERT INTO socrbase VALUES ('4', 'снт', 'Садовое неком-е товарищество', '441');
INSERT INTO socrbase VALUES ('4', 'ст', 'Станция', '432');
INSERT INTO socrbase VALUES ('4', 'ст-ца', 'Станица', '433');
INSERT INTO socrbase VALUES ('4', 'тер', 'Территория', '437');
INSERT INTO socrbase VALUES ('4', 'у', 'Улус', '434');
INSERT INTO socrbase VALUES ('4', 'х', 'Хутор', '435');
INSERT INTO socrbase VALUES ('5', 'аал', 'Аал', '532');
INSERT INTO socrbase VALUES ('5', 'аллея', 'Аллея', '501');
INSERT INTO socrbase VALUES ('5', 'арбан', 'Арбан', '560');
INSERT INTO socrbase VALUES ('5', 'аул', 'Аул', '533');
INSERT INTO socrbase VALUES ('5', 'б-р', 'Бульвар', '502');
INSERT INTO socrbase VALUES ('5', 'вал', 'Вал', '568');
INSERT INTO socrbase VALUES ('5', 'въезд', 'Въезд', '503');
INSERT INTO socrbase VALUES ('5', 'высел', 'Выселки(ок)', '534');
INSERT INTO socrbase VALUES ('5', 'городок', 'Городок', '535');
INSERT INTO socrbase VALUES ('5', 'гск', 'Гаражно-строительный кооперат', '563');
INSERT INTO socrbase VALUES ('5', 'д', 'Деревня', '536');
INSERT INTO socrbase VALUES ('5', 'дор', 'Дорога', '504');
INSERT INTO socrbase VALUES ('5', 'ж/д_будка', 'Железнодорожная будка', '537');
INSERT INTO socrbase VALUES ('5', 'ж/д_казарм', 'Железнодорожная казарма', '538');
INSERT INTO socrbase VALUES ('5', 'ж/д_оп', 'ж/д останов. (обгонный) пункт', '539');
INSERT INTO socrbase VALUES ('5', 'ж/д_платф', 'Железнодорожная платформа', '559');
INSERT INTO socrbase VALUES ('5', 'ж/д_пост', 'Железнодорожный пост', '540');
INSERT INTO socrbase VALUES ('5', 'ж/д_рзд', 'Железнодорожный разъезд', '541');
INSERT INTO socrbase VALUES ('5', 'ж/д_ст', 'Железнодорожная станция', '542');
INSERT INTO socrbase VALUES ('5', 'жт', 'Животноводческая точка', '505');
INSERT INTO socrbase VALUES ('5', 'заезд', 'Заезд', '506');
INSERT INTO socrbase VALUES ('5', 'казарма', 'Казарма', '543');
INSERT INTO socrbase VALUES ('5', 'канал', 'Канал', '562');
INSERT INTO socrbase VALUES ('5', 'кв-л', 'Квартал', '507');
INSERT INTO socrbase VALUES ('5', 'км', 'Километр', '508');
INSERT INTO socrbase VALUES ('5', 'кольцо', 'Кольцо', '509');
INSERT INTO socrbase VALUES ('5', 'коса', 'Коса', '567');
INSERT INTO socrbase VALUES ('5', 'линия', 'Линия', '510');
INSERT INTO socrbase VALUES ('5', 'лпх', 'Леспромхоз', '565');
INSERT INTO socrbase VALUES ('5', 'м', 'Местечко', '544');
INSERT INTO socrbase VALUES ('5', 'мкр', 'Микрорайон', '545');
INSERT INTO socrbase VALUES ('5', 'мост', 'Мост', '570');
INSERT INTO socrbase VALUES ('5', 'наб', 'Набережная', '511');
INSERT INTO socrbase VALUES ('5', 'нп', 'Населенный пункт', '546');
INSERT INTO socrbase VALUES ('5', 'остров', 'Остров', '512');
INSERT INTO socrbase VALUES ('5', 'п', 'Поселок', '548');
INSERT INTO socrbase VALUES ('5', 'п/о', 'Почтовое отделение', '549');
INSERT INTO socrbase VALUES ('5', 'п/р', 'Планировочный район', '550');
INSERT INTO socrbase VALUES ('5', 'п/ст', 'Поселок и(при) станция(и)', '551');
INSERT INTO socrbase VALUES ('5', 'парк', 'Парк', '513');
INSERT INTO socrbase VALUES ('5', 'пер', 'Переулок', '514');
INSERT INTO socrbase VALUES ('5', 'переезд', 'Переезд', '515');
INSERT INTO socrbase VALUES ('5', 'пл', 'Площадь', '516');
INSERT INTO socrbase VALUES ('5', 'пл-ка', 'Площадка', '517');
INSERT INTO socrbase VALUES ('5', 'платф', 'Платформа', '547');
INSERT INTO socrbase VALUES ('5', 'полустанок', 'Полустанок', '552');
INSERT INTO socrbase VALUES ('5', 'починок', 'Починок', '553');
INSERT INTO socrbase VALUES ('5', 'пр-кт', 'Проспект', '519');
INSERT INTO socrbase VALUES ('5', 'проезд', 'Проезд', '518');
INSERT INTO socrbase VALUES ('5', 'просек', 'Просек', '520');
INSERT INTO socrbase VALUES ('5', 'проселок', 'Проселок', '521');
INSERT INTO socrbase VALUES ('5', 'проток', 'Проток', '566');
INSERT INTO socrbase VALUES ('5', 'проулок', 'Проулок', '522');
INSERT INTO socrbase VALUES ('5', 'рзд', 'Разъезд', '554');
INSERT INTO socrbase VALUES ('5', 'с', 'Село', '555');
INSERT INTO socrbase VALUES ('5', 'сад', 'Сад', '523');
INSERT INTO socrbase VALUES ('5', 'сквер', 'Сквер', '524');
INSERT INTO socrbase VALUES ('5', 'сл', 'Слобода', '556');
INSERT INTO socrbase VALUES ('5', 'снт', 'Садовое неком-е товарищество', '564');
INSERT INTO socrbase VALUES ('5', 'спуск', 'Спуск', '561');
INSERT INTO socrbase VALUES ('5', 'ст', 'Станция', '557');
INSERT INTO socrbase VALUES ('5', 'стр', 'Строение', '525');
INSERT INTO socrbase VALUES ('5', 'тер', 'Территория', '526');
INSERT INTO socrbase VALUES ('5', 'тракт', 'Тракт', '527');
INSERT INTO socrbase VALUES ('5', 'туп', 'Тупик', '528');
INSERT INTO socrbase VALUES ('5', 'ул', 'Улица', '529');
INSERT INTO socrbase VALUES ('5', 'уч-к', 'Участок', '530');
INSERT INTO socrbase VALUES ('5', 'ферма', 'Ферма', '569');
INSERT INTO socrbase VALUES ('5', 'х', 'Хутор', '558');
INSERT INTO socrbase VALUES ('5', 'ш', 'Шоссе', '531');
INSERT INTO socrbase VALUES ('6', 'ДОМ', 'Дом', '601');
INSERT INTO socrbase VALUES ('5', 'ряды', 'Ряды', '571');
INSERT INTO socrbase VALUES ('4', 'автодорога', 'Автодорога', '445');
INSERT INTO socrbase VALUES ('5', 'а/я', 'Абонентский ящик', '572');
INSERT INTO socrbase VALUES ('3', 'массив', 'Массив', '316');
INSERT INTO socrbase VALUES ('4', 'жилрайон', 'Жилой район', '446');
INSERT INTO socrbase VALUES ('5', 'берег', 'Берег', '573');
INSERT INTO socrbase VALUES ('1', 'Чувашия', 'Чувашия', '108');
INSERT INTO socrbase VALUES ('5', 'просека', 'Просека', '574');
INSERT INTO socrbase VALUES ('5', 'протока', 'Протока', '575');
INSERT INTO socrbase VALUES ('5', 'бугор', 'Бугор', '576');
INSERT INTO socrbase VALUES ('4', 'жилзона', 'Жилая зона', '447');
INSERT INTO socrbase VALUES ('4', 'массив', 'Массив', '448');
INSERT INTO socrbase VALUES ('3', 'п', 'Поселок', '317');
INSERT INTO socrbase VALUES ('5', 'зона', 'Зона', '577');
